# Generated by Django 5.2.4 on 2025-08-27 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes_app', '0001_initial'),
        ('subjects_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewStdRegModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sur_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=100)),
                ('previous_school', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('birth_citizen_no', models.CharField(max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female'), ('others', 'others')], max_length=10)),
                ('birth_certificate', models.ImageField(blank=True, null=True, upload_to='documents/birth_certificate/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='documents/photos')),
                ('parents_name', models.CharField(max_length=50)),
                ('p_phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('createstudent_fk_createclassmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes_app.createclassmodel')),
                ('createstudent_fk_createsubject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects_app.createsubject')),
            ],
        ),
    ]
