# Generated by Django 5.2.4 on 2025-08-27 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name_model', models.CharField(max_length=50)),
                ('subject_code_model', models.CharField(max_length=10)),
                ('createsubject_fk_createclassmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes_app.createclassmodel')),
            ],
        ),
    ]
