# Generated by Django 5.2.4 on 2025-08-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createsubject',
            name='Subject_max_marks_model',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
