# Generated by Django 5.2.4 on 2025-08-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name_model', models.CharField(max_length=50)),
                ('class_numeric_model', models.IntegerField()),
                ('class_section_model', models.CharField(max_length=20)),
                ('creation_date_model', models.DateTimeField(auto_now_add=True)),
                ('update_date_model', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
