# Generated by Django 5.2.4 on 2025-08-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createclassmodel',
            name='update_date_model',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
